name: 'Terraform Infrasture Pipeline'
# secrets:
#   AWS_BUCKET_KEY: ${{secrets.AWS_BUCKET_KEY}}
#   S3_BACKEND_BUCKET: ${{secrets.S3_BACKEND_BUCKET}}
#   AWS_REGION: ${{secrets.AWS_REGION}}
#   AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
#   AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY_ID}}

on:
  push:
    branches: [ 'dev', 'main' ]
  pull_request:
    branches: [ 'dev', 'main' ]
permissions:
  contents: read
jobs:
  github:
    name: 'Github Actions Setup'
    runs-on: ubuntu-latest
    steps:
    - name: Branch check to determine environment 
      id: branch_check
      run: |
        echo "Running on branch ${{ github.ref }}"
        if ["${{ github.ref }}" = "refs/heads/main"]; then
          echo "::set-output name=env_name::Production"
        else
          echo "::set-output name=env_name::Preview"
        fi
  outputs:
    env_name: ${{ steps.branch_check.outputs.env_name }}

  terraform:
    name: 'Terraform'
    needs: [github]
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.github.outputs.env_name }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false
    - name: Terraform init, format and validate
      run: |
        echo "** Running Terraform Init **"
        terraform init \
          -backend-config="bucket=${{secrets.S3_BACKEND_BUCKET}}" \
          -backend-config="key=state-files" \
          -backend-config="region=${{secrets.AWS_REGION}}"
        echo "** Runing Terraform Format Check **"
        terraform fmt
        echo "** Running Terraform Validate **"
        terraform validate
      working-directory: './deployment'
    - name: Terraform Plan And Apply
      run: |
        echo "** Running Terraform Plan **"
        terraform plan -var 'aws_secret_key=${{secrets.AWS_SECRET_ACCESS_KEY}}' -var 'aws_access_key=${{secrets.AWS_ACCESS_KEY_ID}}'
        
        echo "** Running Terraform Apply **"
        terraform apply -var 'aws_secret_key=${{secrets.AWS_SECRET_ACCESS_KEY}}' -var 'aws_access_key=${{secrets.AWS_ACCESS_KEY_ID}}' -auto-approve
      working-directory: './deployment' 
      

      ##wite test for signed url

      ## write test for deployed server
